"""baseline schema (17 tables)

Revision ID: 0be2c9995936
Revises: 
Create Date: 2026-09-12 03:04:59.710381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.crypto   # EncryptedString：api_key / 告警 webhook 的透明加解密列


revision: str = '0be2c9995936'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_docs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('format', sa.String(length=32), nullable=True),
    sa.Column('base_url', sa.String(length=512), nullable=True),
    sa.Column('spec', sa.JSON(), nullable=True),
    sa.Column('endpoints_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_endpoints',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('doc_id', sa.String(length=64), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_elements',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('page_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=True),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.Column('selector', sa.String(length=512), nullable=True),
    sa.Column('href', sa.String(length=512), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=True),
    sa.Column('state_note', sa.String(length=255), nullable=True),
    sa.Column('roles', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_elements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_elements_page_id'), ['page_id'], unique=False)

    op.create_table('app_pages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=True),
    sa.Column('roles', sa.String(length=255), nullable=True),
    sa.Column('scanned_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_pages_project_id'), ['project_id'], unique=False)

    op.create_table('commit_syncs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('repo_id', sa.String(length=64), nullable=False),
    sa.Column('sha', sa.String(length=40), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=True),
    sa.Column('message', sa.String(length=512), nullable=True),
    sa.Column('branch', sa.String(length=128), nullable=True),
    sa.Column('files', sa.JSON(), nullable=True),
    sa.Column('analyzed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('envs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flows',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('roles', sa.JSON(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('git_repos',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('repo_url', sa.String(length=512), nullable=True),
    sa.Column('webhook_secret', sa.String(length=64), nullable=True),
    sa.Column('default_branch', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('vendor', sa.String(length=64), nullable=True),
    sa.Column('url_type', sa.String(length=16), nullable=True),
    sa.Column('base_url', sa.String(length=512), nullable=True),
    sa.Column('api_key', app.crypto.EncryptedString(length=1024), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('vision', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_logs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notify_channels',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('url', app.crypto.EncryptedString(length=1024), nullable=False),
    sa.Column('on_fail', sa.Boolean(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('last_status', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_members',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_users_project_id'), ['project_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedules',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=False),
    sa.Column('cron', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_cases',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=True),
    sa.Column('creator_id', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_plans',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('case_ids', sa.JSON(), nullable=True),
    sa.Column('flow_ids', sa.JSON(), nullable=True),
    sa.Column('env_id', sa.String(length=64), nullable=True),
    sa.Column('trigger', sa.String(length=16), nullable=True),
    sa.Column('cron', sa.String(length=64), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=True),
    sa.Column('plan_name', sa.String(length=255), nullable=True),
    sa.Column('case_id', sa.String(length=64), nullable=True),
    sa.Column('case_name', sa.String(length=255), nullable=True),
    sa.Column('flow_id', sa.String(length=64), nullable=True),
    sa.Column('flow_name', sa.String(length=255), nullable=True),
    sa.Column('env_id', sa.String(length=64), nullable=True),
    sa.Column('env_name', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('pass_n', sa.Integer(), nullable=True),
    sa.Column('fail_n', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('trigger_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('test_runs')
    op.drop_table('test_plans')
    op.drop_table('test_cases')
    op.drop_table('schedules')
    op.drop_table('projects')
    with op.batch_alter_table('project_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_users_project_id'))

    op.drop_table('project_users')
    op.drop_table('project_members')
    op.drop_table('notify_channels')
    op.drop_table('llm_logs')
    op.drop_table('llm_configs')
    op.drop_table('git_repos')
    op.drop_table('flows')
    op.drop_table('envs')
    op.drop_table('commit_syncs')
    with op.batch_alter_table('app_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_pages_project_id'))

    op.drop_table('app_pages')
    with op.batch_alter_table('app_elements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_elements_page_id'))

    op.drop_table('app_elements')
    op.drop_table('api_endpoints')
    op.drop_table('api_docs')
    # ### end Alembic commands ###
